export type RecipeCategory = "Breakfast" | "Lunch" | "Dinner" | "Snacks";

export type Ingredient = {
  item: string;
  qty: string;
  note?: string;
};

export type RecipeStep = {
  title: string;
  body: string;
  timer?: { seconds: number; label: string };
};

export type Recipe = {
  slug: string;
  name: string;
  category: RecipeCategory;
  angle: string;
  calories: [number, number];
  protein: [number, number];
  minutes: number;
  tags: string[];
  ingredients?: Ingredient[];
  steps?: RecipeStep[];
};

export const RECIPES: Recipe[] = [
  // Breakfast
  {
    slug: "smoothie-bowl",
    name: "Smoothie bowl",
    category: "Breakfast",
    angle: "Sweet, cold, filling",
    calories: [350, 500],
    protein: [25, 40],
    minutes: 3,
    tags: ["No cook", "Sweet"],
    ingredients: [
      { item: "Frozen banana", qty: "1" },
      { item: "Frozen berries", qty: "1 cup" },
      { item: "Greek yogurt", qty: "3/4 cup", note: "0% fat" },
      { item: "Vanilla protein powder", qty: "1 scoop" },
      { item: "Milk", qty: "1/4 cup", note: "or oat milk" },
      { item: "Granola", qty: "2 tbsp", note: "for topping" },
    ],
    steps: [
      { title: "Load the blender", body: "Drop the frozen banana, berries, yogurt, protein powder, and milk into the blender." },
      { title: "Blend thick", body: "Blend on low, pushing down with a tamper or spatula, until thick and smooth. Stop while it still mounds on a spoon." },
      { title: "Spoon and top", body: "Spoon into a bowl, smooth the top, and scatter granola across in one strip." },
    ],
  },
  {
    slug: "yogurt-berry-bowl",
    name: "Greek yogurt berry bowl",
    category: "Breakfast",
    angle: "Fastest protein win",
    calories: [250, 450],
    protein: [25, 40],
    minutes: 2,
    tags: ["No cook"],
    ingredients: [
      { item: "Greek yogurt", qty: "1 cup", note: "0% or 2%" },
      { item: "Mixed berries", qty: "3/4 cup", note: "fresh or thawed" },
      { item: "Vanilla protein powder", qty: "1 scoop", note: "optional" },
      { item: "Honey", qty: "1 tsp" },
      { item: "Granola", qty: "2 tbsp" },
      { item: "Chia seeds", qty: "1 tsp" },
    ],
    steps: [
      { title: "Whisk the base", body: "Spoon the Greek yogurt into a bowl. If using protein powder, stir it in with a splash of water until smooth and no streaks remain." },
      { title: "Add the berries", body: "Pile the mixed berries over the yogurt, keeping them to one side so the bowl looks full." },
      { title: "Top and finish", body: "Drizzle the honey across, scatter the granola and chia seeds, and eat right away while the granola is still crunchy." },
    ],
  },
  {
    slug: "turkey-egg-wrap",
    name: "Turkey egg breakfast wrap",
    category: "Breakfast",
    angle: "Portable & savory",
    calories: [400, 600],
    protein: [35, 50],
    minutes: 10,
    tags: ["Savory"],
    ingredients: [
      { item: "Large tortilla", qty: "1", note: "whole wheat" },
      { item: "Eggs", qty: "2" },
      { item: "Egg whites", qty: "2" },
      { item: "Sliced turkey breast", qty: "60g" },
      { item: "Shredded cheese", qty: "2 tbsp" },
      { item: "Spinach", qty: "1 handful" },
      { item: "Olive oil", qty: "1 tsp" },
      { item: "Salt + pepper", qty: "to taste" },
    ],
    steps: [
      { title: "Heat the pan", body: "Set a nonstick pan over medium heat and add the olive oil." },
      { title: "Cook the eggs", body: "Beat the eggs and egg whites with a pinch of salt and pepper, pour into the pan, and stir gently until just set but still soft." },
      { title: "Warm the fillings", body: "Push the eggs to one side, add the turkey and spinach, and let the spinach wilt for about thirty seconds." },
      { title: "Build the wrap", body: "Lay the tortilla flat, spoon the eggs, turkey, and spinach down the center, and scatter the cheese over the top while it's hot." },
      { title: "Roll and toast", body: "Fold in the sides and roll it tight. Set the wrap seam-side down in the pan for one minute to seal, then slice in half." },
    ],
  },
  {
    slug: "protein-oats",
    name: "Protein oats with banana",
    category: "Breakfast",
    angle: "Pre-training fuel",
    calories: [400, 550],
    protein: [25, 40],
    minutes: 5,
    tags: ["Pre-workout"],
    ingredients: [
      { item: "Rolled oats", qty: "1/2 cup" },
      { item: "Milk", qty: "1 cup", note: "or oat milk" },
      { item: "Vanilla protein powder", qty: "1 scoop" },
      { item: "Banana", qty: "1", note: "half sliced for topping" },
      { item: "Peanut butter", qty: "1 tbsp" },
      { item: "Cinnamon", qty: "1 pinch" },
    ],
    steps: [
      {
        title: "Cook the oats",
        body: "Combine the oats and milk in a small pot over medium heat. Stir often until thick and creamy, about three minutes.",
        timer: { seconds: 180, label: "Oats simmer" },
      },
      { title: "Cool slightly", body: "Take the pot off the heat and let it sit for one minute so it's warm, not scalding — protein powder clumps in boiling liquid." },
      { title: "Stir in protein", body: "Add the protein powder and a pinch of cinnamon, stirring hard until fully smooth." },
      { title: "Top and serve", body: "Spoon into a bowl, fan the banana slices across the top, and finish with a swirl of peanut butter." },
    ],
  },
  {
    slug: "cottage-toast",
    name: "Cottage cheese toast with egg",
    category: "Breakfast",
    angle: "Quick & savory",
    calories: [350, 500],
    protein: [25, 40],
    minutes: 8,
    tags: ["Savory"],
    ingredients: [
      { item: "Bread", qty: "2 slices", note: "whole grain" },
      { item: "Cottage cheese", qty: "1/2 cup" },
      { item: "Egg", qty: "1" },
      { item: "Cherry tomatoes", qty: "5", note: "halved" },
      { item: "Olive oil", qty: "1 tsp" },
      { item: "Salt + pepper", qty: "to taste" },
      { item: "Chili flakes", qty: "1 pinch" },
    ],
    steps: [
      { title: "Toast the bread", body: "Drop the bread into the toaster and toast until golden and firm enough to hold a topping." },
      { title: "Fry the egg", body: "Heat the olive oil in a small pan over medium heat and fry the egg to your liking, about two minutes for a runny yolk." },
      { title: "Spread the base", body: "Spread the cottage cheese thickly over both slices of warm toast." },
      { title: "Top it", body: "Scatter the halved cherry tomatoes over the cottage cheese and slide the fried egg on top." },
      { title: "Season", body: "Finish with salt, pepper, and a pinch of chili flakes." },
    ],
  },
  {
    slug: "egg-white-scramble",
    name: "Egg white & whole egg scramble",
    category: "Breakfast",
    angle: "Lighter, not dry",
    calories: [250, 400],
    protein: [30, 45],
    minutes: 8,
    tags: ["Lower cal"],
    ingredients: [
      { item: "Egg whites", qty: "4" },
      { item: "Whole egg", qty: "1" },
      { item: "Spinach", qty: "1 large handful" },
      { item: "Cherry tomatoes", qty: "6", note: "halved" },
      { item: "Feta", qty: "2 tbsp", note: "crumbled" },
      { item: "Olive oil", qty: "1 tsp" },
      { item: "Salt + pepper", qty: "to taste" },
    ],
    steps: [
      { title: "Prep the eggs", body: "Whisk the egg whites and whole egg together with a pinch of salt and pepper until even in color." },
      { title: "Soften the veg", body: "Heat the olive oil in a nonstick pan over medium heat, add the tomatoes and spinach, and cook until the spinach wilts, about a minute." },
      { title: "Add the eggs", body: "Pour the eggs over the vegetables and let them sit for ten seconds before stirring." },
      { title: "Scramble soft", body: "Stir slowly, pulling the eggs into folds, and take the pan off the heat while they still look slightly wet — they finish on the plate." },
      { title: "Finish", body: "Slide onto a plate and crumble the feta over the top." },
    ],
  },
  {
    slug: "potato-turkey-skillet",
    name: "Breakfast potato turkey skillet",
    category: "Breakfast",
    angle: "Post-workout fill-up",
    calories: [500, 700],
    protein: [35, 50],
    minutes: 25,
    tags: ["Post-workout"],
    ingredients: [
      { item: "Potatoes", qty: "2 medium", note: "diced small" },
      { item: "Ground turkey", qty: "200g" },
      { item: "Onion", qty: "1/2", note: "diced" },
      { item: "Bell pepper", qty: "1", note: "diced" },
      { item: "Eggs", qty: "2" },
      { item: "Olive oil", qty: "1 tbsp" },
      { item: "Paprika", qty: "1 tsp" },
      { item: "Salt + pepper", qty: "to taste" },
    ],
    steps: [
      {
        title: "Crisp the potatoes",
        body: "Heat the olive oil in a large skillet over medium-high. Add the diced potatoes, season with salt, and cook undisturbed for a few minutes, then stir until golden, about ten minutes total.",
        timer: { seconds: 600, label: "Potatoes crisp" },
      },
      { title: "Add aromatics", body: "Push the potatoes aside, add the onion and bell pepper, and cook until softened, about three minutes." },
      {
        title: "Brown the turkey",
        body: "Add the ground turkey and paprika. Break it up with a spoon and cook until no pink remains, about five minutes.",
        timer: { seconds: 300, label: "Turkey brown" },
      },
      {
        title: "Make wells",
        body: "Flatten the mixture and make two wells. Crack an egg into each, cover the pan, and cook until the whites set, about three minutes.",
        timer: { seconds: 180, label: "Eggs set" },
      },
      { title: "Serve", body: "Season with salt and pepper and serve straight from the skillet." },
    ],
  },
  {
    slug: "banana-pancakes",
    name: "High-protein banana pancakes",
    category: "Breakfast",
    angle: "Sweet, still macros",
    calories: [400, 600],
    protein: [25, 40],
    minutes: 12,
    tags: ["Sweet"],
    ingredients: [
      { item: "Banana", qty: "1", note: "ripe, plus extra to top" },
      { item: "Eggs", qty: "2" },
      { item: "Vanilla protein powder", qty: "1 scoop" },
      { item: "Rolled oats", qty: "1/4 cup" },
      { item: "Baking powder", qty: "1/2 tsp" },
      { item: "Milk", qty: "2 tbsp" },
      { item: "Olive oil spray", qty: "as needed" },
    ],
    steps: [
      { title: "Blend the batter", body: "Add the banana, eggs, protein powder, oats, baking powder, and milk to a blender and blend until smooth. Let it rest two minutes to thicken." },
      { title: "Heat the pan", body: "Set a nonstick pan over medium-low heat and mist lightly with oil. Low and slow keeps protein pancakes from burning." },
      {
        title: "Pour the pancakes",
        body: "Pour small pools of batter, about three inches wide, and cook until bubbles form on top, about two minutes.",
        timer: { seconds: 120, label: "First side" },
      },
      { title: "Flip", body: "Flip each pancake and cook another minute until set and golden underneath." },
      { title: "Stack and serve", body: "Stack the pancakes, top with extra banana slices, and serve." },
    ],
  },
  {
    slug: "salmon-egg-toast",
    name: "Smoked salmon egg toast",
    category: "Breakfast",
    angle: "Café energy, real protein",
    calories: [350, 500],
    protein: [25, 40],
    minutes: 8,
    tags: ["Savory"],
    ingredients: [
      { item: "Bread", qty: "2 slices", note: "sourdough" },
      { item: "Smoked salmon", qty: "80g" },
      { item: "Eggs", qty: "2" },
      { item: "Cream cheese", qty: "2 tbsp" },
      { item: "Lemon", qty: "1/2" },
      { item: "Dill", qty: "1 tsp", note: "chopped" },
      { item: "Black pepper", qty: "to taste" },
    ],
    steps: [
      {
        title: "Boil the eggs",
        body: "Lower the eggs into simmering water and cook for seven minutes for jammy yolks, then move them to cold water.",
        timer: { seconds: 420, label: "Eggs boil" },
      },
      { title: "Toast and spread", body: "Toast the bread, then spread cream cheese over each warm slice." },
      { title: "Layer the salmon", body: "Drape the smoked salmon over the cream cheese in loose folds." },
      { title: "Add the eggs", body: "Peel the eggs, slice them in half, and lay them over the salmon." },
      { title: "Finish", body: "Squeeze the lemon over the top, scatter the dill, and crack black pepper across." },
    ],
  },
  {
    slug: "tofu-scramble",
    name: "Tofu breakfast scramble",
    category: "Breakfast",
    angle: "Veggie & high protein",
    calories: [300, 500],
    protein: [25, 40],
    minutes: 10,
    tags: ["Vegetarian"],
    ingredients: [
      { item: "Firm tofu", qty: "200g", note: "pressed" },
      { item: "Turmeric", qty: "1/4 tsp" },
      { item: "Nutritional yeast", qty: "1 tbsp" },
      { item: "Spinach", qty: "1 handful" },
      { item: "Cherry tomatoes", qty: "6", note: "halved" },
      { item: "Olive oil", qty: "1 tbsp" },
      { item: "Salt + pepper", qty: "to taste" },
    ],
    steps: [
      { title: "Crumble the tofu", body: "Press the tofu dry and crumble it into rough, egg-sized pieces with your hands." },
      { title: "Heat the pan", body: "Warm the olive oil in a nonstick pan over medium heat." },
      { title: "Cook the tofu", body: "Add the tofu, turmeric, and a pinch of salt. Stir occasionally until the tofu is hot and lightly golden, about four minutes." },
      { title: "Add the veg", body: "Stir in the tomatoes and spinach and cook until the spinach wilts, about two minutes." },
      { title: "Finish", body: "Sprinkle the nutritional yeast over, season with pepper, and toss once before serving." },
    ],
  },

  // Lunch
  {
    slug: "chicken-rice-bowl",
    name: "Chicken rice power bowl",
    category: "Lunch",
    angle: "Balanced classic",
    calories: [500, 700],
    protein: [40, 55],
    minutes: 25,
    tags: ["Meal prep"],
    ingredients: [
      { item: "Chicken breast", qty: "200g", note: "cut into bite-size cubes" },
      { item: "Jasmine rice", qty: "3/4 cup", note: "uncooked" },
      { item: "Olive oil", qty: "1 tbsp" },
      { item: "Garlic", qty: "2 cloves", note: "minced" },
      { item: "Soy sauce", qty: "1 tbsp", note: "low-sodium" },
      { item: "Cucumber", qty: "1/2", note: "diced" },
      { item: "Avocado", qty: "1/2", note: "sliced" },
      { item: "Salt + pepper", qty: "to taste" },
      { item: "Lime", qty: "1/2", note: "for finishing" },
    ],
    steps: [
      {
        title: "Start the rice",
        body: "Rinse the rice until the water runs clear, then add it to a pot with one and a half cups of water and a pinch of salt. Bring to a boil, cover, and lower the heat.",
        timer: { seconds: 900, label: "Rice simmer" },
      },
      { title: "Season the chicken", body: "While the rice cooks, pat the chicken dry, then toss with olive oil, salt, pepper, and half the garlic." },
      { title: "Heat the pan", body: "Set a large pan over medium-high heat. Let it get hot enough that a drop of water sizzles on contact." },
      {
        title: "Sear the chicken",
        body: "Add the chicken in one layer. Don't move it for ninety seconds, then stir occasionally until golden and cooked through, about six minutes total.",
        timer: { seconds: 360, label: "Chicken sear" },
      },
      { title: "Build the sauce", body: "Lower the heat, add the rest of the garlic and the soy sauce, and toss for thirty seconds until glossy." },
      { title: "Prep the cold side", body: "While the chicken finishes, dice the cucumber and slice the avocado. Squeeze the lime over both." },
      { title: "Assemble the bowl", body: "Spoon rice into a wide bowl, lay the chicken on one side, and pile the cucumber and avocado on the other." },
      { title: "Finish", body: "Top with the remaining lime, a pinch of flaky salt, and a quick crack of black pepper. Done." },
    ],
  },
  {
    slug: "turkey-avocado-wrap",
    name: "Turkey avocado lunch wrap",
    category: "Lunch",
    angle: "Done in five",
    calories: [400, 600],
    protein: [30, 45],
    minutes: 5,
    tags: ["Fast"],
    ingredients: [
      { item: "Large tortilla", qty: "1" },
      { item: "Sliced turkey breast", qty: "100g" },
      { item: "Avocado", qty: "1/2" },
      { item: "Lettuce", qty: "2 leaves" },
      { item: "Tomato", qty: "1/2", note: "sliced" },
      { item: "Mustard", qty: "1 tsp" },
      { item: "Salt + pepper", qty: "to taste" },
    ],
    steps: [
      { title: "Mash the avocado", body: "Scoop the avocado onto the tortilla and mash it across with a fork, leaving a clear border." },
      { title: "Layer the fillings", body: "Lay the turkey, lettuce, and tomato down the center of the tortilla." },
      { title: "Season", body: "Add the mustard, a pinch of salt, and pepper over the filling." },
      { title: "Roll", body: "Fold in the sides and roll the wrap tight, then slice in half on the diagonal." },
    ],
  },
  {
    slug: "tuna-rice-bowl",
    name: "Tuna rice cucumber bowl",
    category: "Lunch",
    angle: "Cheap & cold-prep",
    calories: [400, 600],
    protein: [30, 45],
    minutes: 5,
    tags: ["Cheap"],
    ingredients: [
      { item: "Cooked rice", qty: "1 cup", note: "warm or cold" },
      { item: "Canned tuna", qty: "1 can", note: "drained" },
      { item: "Cucumber", qty: "1/2", note: "diced" },
      { item: "Mayo", qty: "1 tbsp" },
      { item: "Soy sauce", qty: "1 tsp" },
      { item: "Sesame seeds", qty: "1 tsp" },
      { item: "Sriracha", qty: "1 tsp", note: "optional" },
    ],
    steps: [
      { title: "Mix the tuna", body: "In a bowl, stir the drained tuna with the mayo, soy sauce, and sriracha until creamy." },
      { title: "Add the rice", body: "Spoon the rice into a serving bowl and spread it flat." },
      { title: "Build the bowl", body: "Pile the tuna mix on one side and the diced cucumber on the other." },
      { title: "Finish", body: "Scatter sesame seeds over the top and serve." },
    ],
  },
  {
    slug: "chicken-caesar",
    name: "Chicken Caesar protein salad",
    category: "Lunch",
    angle: "A salad that fills you",
    calories: [400, 650],
    protein: [40, 55],
    minutes: 8,
    tags: ["Salad"],
    ingredients: [
      { item: "Cooked chicken breast", qty: "200g", note: "sliced" },
      { item: "Romaine lettuce", qty: "1 head", note: "chopped" },
      { item: "Caesar dressing", qty: "2 tbsp", note: "light" },
      { item: "Parmesan", qty: "2 tbsp", note: "grated" },
      { item: "Croutons", qty: "1/4 cup" },
      { item: "Lemon", qty: "1/2" },
      { item: "Black pepper", qty: "to taste" },
    ],
    steps: [
      { title: "Prep the lettuce", body: "Chop the romaine and add it to a large bowl." },
      { title: "Dress it", body: "Add the Caesar dressing and toss until every leaf is lightly coated." },
      { title: "Add the chicken", body: "Lay the sliced chicken over the leaves." },
      { title: "Finish", body: "Scatter the parmesan and croutons, squeeze the lemon over, and crack black pepper across the top." },
    ],
  },
  {
    slug: "egg-potato-plate",
    name: "Egg & potato lunch plate",
    category: "Lunch",
    angle: "Pantry-only",
    calories: [450, 650],
    protein: [25, 40],
    minutes: 22,
    tags: ["Cheap"],
    ingredients: [
      { item: "Potatoes", qty: "2 medium" },
      { item: "Eggs", qty: "3" },
      { item: "Olive oil", qty: "1 tbsp" },
      { item: "Paprika", qty: "1 tsp" },
      { item: "Parsley", qty: "1 tbsp", note: "chopped" },
      { item: "Salt + pepper", qty: "to taste" },
    ],
    steps: [
      {
        title: "Boil the potatoes",
        body: "Cut the potatoes into chunks and add them to a pot of salted water. Bring to a boil and cook until fork-tender, about fifteen minutes.",
        timer: { seconds: 900, label: "Potatoes boil" },
      },
      {
        title: "Boil the eggs",
        body: "In the last ten minutes, lower the eggs into the same pot and cook for ten minutes, then move them to cold water.",
        timer: { seconds: 600, label: "Eggs boil" },
      },
      { title: "Crisp the potatoes", body: "Drain the potatoes, heat the olive oil in a pan, and fry them with the paprika until the edges turn golden, about five minutes." },
      { title: "Plate it", body: "Peel and quarter the eggs and arrange them next to the potatoes." },
      { title: "Finish", body: "Season everything with salt and pepper and scatter the parsley over the top." },
    ],
  },
  {
    slug: "salmon-rice-bowl",
    name: "Salmon rice bowl",
    category: "Lunch",
    angle: "Protein + healthy fats",
    calories: [550, 750],
    protein: [35, 50],
    minutes: 15,
    tags: ["Omega-3"],
    ingredients: [
      { item: "Salmon fillet", qty: "180g" },
      { item: "Cooked rice", qty: "1 cup" },
      { item: "Avocado", qty: "1/2", note: "sliced" },
      { item: "Cucumber", qty: "1/2", note: "sliced" },
      { item: "Soy sauce", qty: "1 tbsp" },
      { item: "Sesame oil", qty: "1 tsp" },
      { item: "Sesame seeds", qty: "1 tsp" },
    ],
    steps: [
      { title: "Heat the pan", body: "Set a nonstick pan over medium-high heat with the sesame oil." },
      {
        title: "Cook the salmon",
        body: "Place the salmon skin-side down and cook for four minutes, then flip and cook another three until it flakes easily.",
        timer: { seconds: 240, label: "Salmon first side" },
      },
      { title: "Warm the rice", body: "Spoon the rice into a bowl while the salmon finishes." },
      { title: "Build the bowl", body: "Flake the salmon over the rice and arrange the avocado and cucumber alongside." },
      { title: "Finish", body: "Drizzle the soy sauce over and scatter the sesame seeds." },
    ],
  },
  {
    slug: "chicken-hummus-pita",
    name: "Chicken hummus pita",
    category: "Lunch",
    angle: "Mediterranean lift",
    calories: [500, 700],
    protein: [35, 50],
    minutes: 7,
    tags: ["Mediterranean"],
    ingredients: [
      { item: "Pita bread", qty: "1", note: "whole wheat" },
      { item: "Cooked chicken breast", qty: "150g", note: "sliced" },
      { item: "Hummus", qty: "3 tbsp" },
      { item: "Cucumber", qty: "1/2", note: "diced" },
      { item: "Cherry tomatoes", qty: "6", note: "halved" },
      { item: "Red onion", qty: "2 tbsp", note: "sliced thin" },
      { item: "Lemon", qty: "1/2" },
    ],
    steps: [
      { title: "Warm the pita", body: "Toast the pita for one minute until soft and warm, then slice it open into a pocket." },
      { title: "Spread the hummus", body: "Spread the hummus generously inside the pocket." },
      { title: "Fill it", body: "Tuck the chicken, cucumber, tomatoes, and red onion into the pita." },
      { title: "Finish", body: "Squeeze the lemon over the filling before serving." },
    ],
  },
  {
    slug: "turkey-burger-bowl",
    name: "Turkey burger bowl",
    category: "Lunch",
    angle: "Burger night, lighter",
    calories: [500, 700],
    protein: [40, 55],
    minutes: 22,
    tags: ["Comfort"],
    ingredients: [
      { item: "Ground turkey", qty: "200g" },
      { item: "Lettuce", qty: "2 cups", note: "shredded" },
      { item: "Tomato", qty: "1", note: "diced" },
      { item: "Pickles", qty: "1/4 cup", note: "sliced" },
      { item: "Cheddar", qty: "2 tbsp", note: "shredded" },
      { item: "Burger sauce", qty: "1 tbsp" },
      { item: "Olive oil", qty: "1 tsp" },
      { item: "Salt + pepper", qty: "to taste" },
    ],
    steps: [
      { title: "Form the patty", body: "Season the ground turkey with salt and pepper and shape it into one thick patty or a few small ones." },
      {
        title: "Cook the turkey",
        body: "Heat the olive oil in a pan over medium-high and cook the patty until browned and cooked through, about five minutes a side.",
        timer: { seconds: 600, label: "Turkey patty" },
      },
      { title: "Build the base", body: "While it cooks, spread the shredded lettuce across a wide bowl." },
      { title: "Add toppings", body: "Scatter the tomato, pickles, and cheddar over the lettuce." },
      { title: "Finish", body: "Slice the turkey, lay it over the bowl, and drizzle the burger sauce across." },
    ],
  },
  {
    slug: "shrimp-quinoa-bowl",
    name: "Shrimp quinoa bowl",
    category: "Lunch",
    angle: "Light but filling",
    calories: [450, 650],
    protein: [35, 50],
    minutes: 12,
    tags: ["Light"],
    ingredients: [
      { item: "Shrimp", qty: "200g", note: "peeled" },
      { item: "Cooked quinoa", qty: "1 cup" },
      { item: "Cherry tomatoes", qty: "8", note: "halved" },
      { item: "Cucumber", qty: "1/2", note: "diced" },
      { item: "Olive oil", qty: "1 tbsp" },
      { item: "Garlic", qty: "1 clove", note: "minced" },
      { item: "Lemon", qty: "1/2" },
      { item: "Salt + pepper", qty: "to taste" },
    ],
    steps: [
      { title: "Heat the pan", body: "Warm the olive oil in a pan over medium-high heat and add the garlic." },
      {
        title: "Cook the shrimp",
        body: "Add the shrimp in one layer and cook until pink and opaque, about two minutes a side.",
        timer: { seconds: 240, label: "Shrimp cook" },
      },
      { title: "Build the base", body: "Spoon the quinoa into a bowl and add the tomatoes and cucumber." },
      { title: "Top it", body: "Lay the cooked shrimp over the quinoa." },
      { title: "Finish", body: "Squeeze the lemon over and season with salt and pepper." },
    ],
  },
  {
    slug: "protein-pasta-salad",
    name: "High-protein pasta salad",
    category: "Lunch",
    angle: "Meal-prep hero",
    calories: [500, 750],
    protein: [35, 55],
    minutes: 18,
    tags: ["Meal prep"],
    ingredients: [
      { item: "Chickpea pasta", qty: "1.5 cups", note: "dry" },
      { item: "Cooked chicken breast", qty: "150g", note: "diced" },
      { item: "Cherry tomatoes", qty: "10", note: "halved" },
      { item: "Cucumber", qty: "1/2", note: "diced" },
      { item: "Mozzarella pearls", qty: "1/4 cup" },
      { item: "Italian dressing", qty: "2 tbsp" },
      { item: "Basil", qty: "1 tbsp", note: "torn" },
    ],
    steps: [
      {
        title: "Boil the pasta",
        body: "Cook the chickpea pasta in salted boiling water until just tender, about ten minutes, then drain.",
        timer: { seconds: 600, label: "Pasta boil" },
      },
      { title: "Cool it down", body: "Rinse the pasta under cold water so it stops cooking and doesn't clump." },
      { title: "Combine", body: "In a large bowl, toss the pasta with the chicken, tomatoes, cucumber, and mozzarella." },
      { title: "Dress it", body: "Pour the Italian dressing over and toss until everything is coated." },
      { title: "Finish", body: "Scatter the torn basil over the top and serve cold." },
    ],
  },

  // Dinner
  {
    slug: "honey-garlic-wings",
    name: "Honey garlic chicken wings",
    category: "Dinner",
    angle: "Comfort, with macros",
    calories: [500, 800],
    protein: [35, 60],
    minutes: 28,
    tags: ["Air fryer"],
    ingredients: [
      { item: "Chicken wings", qty: "600g" },
      { item: "Honey", qty: "2 tbsp" },
      { item: "Soy sauce", qty: "2 tbsp" },
      { item: "Garlic", qty: "3 cloves", note: "minced" },
      { item: "Olive oil", qty: "1 tbsp" },
      { item: "Salt + pepper", qty: "to taste" },
      { item: "Sesame seeds", qty: "1 tsp" },
    ],
    steps: [
      { title: "Preheat", body: "Preheat the air fryer to two hundred degrees Celsius, four hundred Fahrenheit." },
      { title: "Season the wings", body: "Pat the wings dry, then toss them with the olive oil, salt, and pepper." },
      {
        title: "Air fry",
        body: "Arrange the wings in one layer and cook for eighteen minutes, flipping halfway, until deep golden and crisp.",
        timer: { seconds: 1080, label: "Air fry wings" },
      },
      {
        title: "Make the glaze",
        body: "While the wings cook, simmer the honey, soy sauce, and garlic in a small pan until slightly thickened, about three minutes.",
        timer: { seconds: 180, label: "Glaze simmer" },
      },
      { title: "Toss and finish", body: "Toss the hot wings in the glaze until fully coated and scatter sesame seeds over." },
    ],
  },
  {
    slug: "chicken-tenders",
    name: "Air fryer chicken tenders",
    category: "Dinner",
    angle: "Crispy, not fried",
    calories: [450, 650],
    protein: [45, 60],
    minutes: 18,
    tags: ["Air fryer"],
    ingredients: [
      { item: "Chicken tenders", qty: "450g" },
      { item: "Egg", qty: "1, beaten" },
      { item: "Panko breadcrumbs", qty: "1 cup" },
      { item: "Parmesan", qty: "2 tbsp", note: "grated" },
      { item: "Garlic powder", qty: "1 tsp" },
      { item: "Paprika", qty: "1 tsp" },
      { item: "Salt + pepper", qty: "to taste" },
      { item: "Olive oil spray", qty: "as needed" },
    ],
    steps: [
      { title: "Preheat", body: "Preheat the air fryer to two hundred degrees Celsius, four hundred Fahrenheit." },
      { title: "Mix the coating", body: "In a wide bowl, mix the panko, parmesan, garlic powder, paprika, salt, and pepper." },
      { title: "Dredge the tenders", body: "Dip each tender in the beaten egg, let the excess drip, then press into the panko mix until fully coated." },
      { title: "Spray and arrange", body: "Spray the basket lightly, lay the tenders in one layer, and mist the tops with oil so they crisp evenly." },
      {
        title: "Air fry",
        body: "Cook for ten minutes, flipping halfway, until the coating is deep golden and the inside reads seventy four degrees Celsius.",
        timer: { seconds: 600, label: "Air fry tenders" },
      },
      { title: "Rest and plate", body: "Let the tenders rest two minutes so the crust stays crisp, then plate with a wedge of lemon." },
    ],
  },
  {
    slug: "turkey-meatballs",
    name: "Turkey meatballs with rice",
    category: "Dinner",
    angle: "Cozy & meal-prep friendly",
    calories: [500, 750],
    protein: [40, 60],
    minutes: 25,
    tags: ["Meal prep"],
    ingredients: [
      { item: "Ground turkey", qty: "400g" },
      { item: "Breadcrumbs", qty: "1/3 cup" },
      { item: "Egg", qty: "1" },
      { item: "Garlic", qty: "2 cloves", note: "minced" },
      { item: "Cooked rice", qty: "1.5 cups" },
      { item: "Marinara sauce", qty: "1 cup" },
      { item: "Olive oil", qty: "1 tbsp" },
      { item: "Salt + pepper", qty: "to taste" },
    ],
    steps: [
      { title: "Mix the meatballs", body: "Combine the ground turkey, breadcrumbs, egg, garlic, salt, and pepper in a bowl and mix just until it holds together." },
      { title: "Roll them", body: "Roll the mixture into meatballs about the size of a golf ball." },
      {
        title: "Sear",
        body: "Heat the olive oil in a pan over medium-high and brown the meatballs on all sides, about five minutes.",
        timer: { seconds: 300, label: "Meatball sear" },
      },
      {
        title: "Simmer in sauce",
        body: "Pour the marinara over the meatballs, lower the heat, cover, and simmer until cooked through, about ten minutes.",
        timer: { seconds: 600, label: "Meatball simmer" },
      },
      { title: "Serve", body: "Spoon the rice onto plates and top with the meatballs and sauce." },
    ],
  },
  {
    slug: "salmon-potatoes",
    name: "Garlic lemon salmon & potatoes",
    category: "Dinner",
    angle: "Omega-3 dinner",
    calories: [550, 800],
    protein: [35, 50],
    minutes: 25,
    tags: ["Omega-3"],
    ingredients: [
      { item: "Salmon fillets", qty: "2", note: "about 180g each" },
      { item: "Baby potatoes", qty: "400g", note: "halved" },
      { item: "Garlic", qty: "3 cloves", note: "minced" },
      { item: "Lemon", qty: "1", note: "sliced" },
      { item: "Olive oil", qty: "2 tbsp" },
      { item: "Parsley", qty: "1 tbsp", note: "chopped" },
      { item: "Salt + pepper", qty: "to taste" },
    ],
    steps: [
      { title: "Preheat", body: "Preheat the oven to two hundred degrees Celsius, four hundred Fahrenheit." },
      {
        title: "Roast the potatoes",
        body: "Toss the halved potatoes with one tablespoon of olive oil and salt, spread them on a tray, and roast for fifteen minutes.",
        timer: { seconds: 900, label: "Potatoes roast" },
      },
      { title: "Prep the salmon", body: "Rub the salmon with the remaining oil, the garlic, salt, and pepper, and top each fillet with a lemon slice." },
      {
        title: "Roast together",
        body: "Slide the salmon onto the tray with the potatoes and roast until the salmon flakes easily, about ten more minutes.",
        timer: { seconds: 600, label: "Salmon roast" },
      },
      { title: "Finish", body: "Scatter the parsley over and serve with the remaining lemon." },
    ],
  },
  {
    slug: "chicken-fajita-bowl",
    name: "Chicken fajita bowl",
    category: "Dinner",
    angle: "Flavor-loaded",
    calories: [500, 700],
    protein: [40, 60],
    minutes: 18,
    tags: ["Bowl"],
    ingredients: [
      { item: "Chicken breast", qty: "250g", note: "sliced" },
      { item: "Bell peppers", qty: "2", note: "sliced" },
      { item: "Onion", qty: "1", note: "sliced" },
      { item: "Cooked rice", qty: "1 cup" },
      { item: "Fajita seasoning", qty: "1 tbsp" },
      { item: "Olive oil", qty: "1 tbsp" },
      { item: "Lime", qty: "1/2" },
      { item: "Salt", qty: "to taste" },
    ],
    steps: [
      { title: "Season the chicken", body: "Toss the sliced chicken with the fajita seasoning and a pinch of salt." },
      { title: "Heat the pan", body: "Warm the olive oil in a large pan over medium-high heat." },
      {
        title: "Cook the chicken",
        body: "Add the chicken and cook until golden and cooked through, about six minutes, then set it aside.",
        timer: { seconds: 360, label: "Chicken cook" },
      },
      {
        title: "Cook the veg",
        body: "In the same pan, cook the peppers and onion until softened and charred at the edges, about five minutes.",
        timer: { seconds: 300, label: "Peppers cook" },
      },
      { title: "Build the bowl", body: "Spoon the rice into a bowl, add the chicken and vegetables, and squeeze the lime over." },
    ],
  },
  {
    slug: "beef-broccoli-bowl",
    name: "Beef & broccoli rice bowl",
    category: "Dinner",
    angle: "Takeout, lighter",
    calories: [550, 750],
    protein: [35, 55],
    minutes: 15,
    tags: ["Takeout-style"],
    ingredients: [
      { item: "Beef strips", qty: "250g" },
      { item: "Broccoli", qty: "2 cups", note: "florets" },
      { item: "Cooked rice", qty: "1 cup" },
      { item: "Soy sauce", qty: "2 tbsp" },
      { item: "Garlic", qty: "2 cloves", note: "minced" },
      { item: "Ginger", qty: "1 tsp", note: "grated" },
      { item: "Cornstarch", qty: "1 tsp" },
      { item: "Sesame oil", qty: "1 tbsp" },
    ],
    steps: [
      { title: "Prep the sauce", body: "Stir the soy sauce, cornstarch, and a splash of water together until smooth." },
      {
        title: "Sear the beef",
        body: "Heat the sesame oil in a pan over high heat and sear the beef strips until browned, about two minutes, then set aside.",
        timer: { seconds: 120, label: "Beef sear" },
      },
      {
        title: "Cook the broccoli",
        body: "Add the broccoli to the pan with a splash of water, cover, and steam until bright green, about three minutes.",
        timer: { seconds: 180, label: "Broccoli steam" },
      },
      { title: "Combine", body: "Return the beef, add the garlic and ginger, pour in the sauce, and toss until everything is glossy." },
      { title: "Serve", body: "Spoon the beef and broccoli over the rice and serve hot." },
    ],
  },
  {
    slug: "chicken-pasta",
    name: "High-protein chicken pasta",
    category: "Dinner",
    angle: "Comfort, kept honest",
    calories: [600, 850],
    protein: [45, 65],
    minutes: 22,
    tags: ["Comfort"],
    ingredients: [
      { item: "Chicken breast", qty: "250g", note: "diced" },
      { item: "Pasta", qty: "2 cups", note: "dry" },
      { item: "Garlic", qty: "3 cloves", note: "minced" },
      { item: "Cherry tomatoes", qty: "1 cup", note: "halved" },
      { item: "Spinach", qty: "2 handfuls" },
      { item: "Parmesan", qty: "1/4 cup", note: "grated" },
      { item: "Olive oil", qty: "1 tbsp" },
      { item: "Salt + pepper", qty: "to taste" },
    ],
    steps: [
      {
        title: "Boil the pasta",
        body: "Cook the pasta in salted boiling water until just tender, then reserve a cup of the cooking water and drain.",
        timer: { seconds: 600, label: "Pasta boil" },
      },
      {
        title: "Cook the chicken",
        body: "Heat the olive oil in a large pan and cook the diced chicken with salt and pepper until golden, about six minutes.",
        timer: { seconds: 360, label: "Chicken cook" },
      },
      { title: "Build the sauce", body: "Add the garlic and tomatoes and cook until the tomatoes soften and burst, about three minutes." },
      { title: "Combine", body: "Add the pasta, spinach, and a splash of the reserved water. Toss until the spinach wilts and the sauce coats the pasta." },
      { title: "Finish", body: "Stir in the parmesan and serve." },
    ],
  },
  {
    slug: "shrimp-tacos",
    name: "Shrimp tacos with yogurt sauce",
    category: "Dinner",
    angle: "Light taco night",
    calories: [450, 650],
    protein: [35, 50],
    minutes: 12,
    tags: ["Tacos"],
    ingredients: [
      { item: "Shrimp", qty: "250g", note: "peeled" },
      { item: "Tortillas", qty: "4", note: "small" },
      { item: "Greek yogurt", qty: "1/3 cup" },
      { item: "Lime", qty: "1" },
      { item: "Cabbage", qty: "1 cup", note: "shredded" },
      { item: "Chili powder", qty: "1 tsp" },
      { item: "Olive oil", qty: "1 tbsp" },
      { item: "Salt", qty: "to taste" },
    ],
    steps: [
      { title: "Make the sauce", body: "Stir the Greek yogurt with the juice of half the lime and a pinch of salt, then set it aside." },
      { title: "Season the shrimp", body: "Toss the shrimp with the chili powder and a pinch of salt." },
      {
        title: "Cook the shrimp",
        body: "Heat the olive oil in a pan over medium-high and cook the shrimp until pink, about two minutes a side.",
        timer: { seconds: 240, label: "Shrimp cook" },
      },
      { title: "Warm the tortillas", body: "Warm the tortillas in a dry pan for about thirty seconds each." },
      { title: "Build the tacos", body: "Fill each tortilla with cabbage and shrimp, drizzle the yogurt sauce over, and finish with a squeeze of lime." },
    ],
  },
  {
    slug: "turkey-stuffed-peppers",
    name: "Turkey stuffed peppers",
    category: "Dinner",
    angle: "Built for leftovers",
    calories: [400, 600],
    protein: [30, 45],
    minutes: 35,
    tags: ["Meal prep"],
    ingredients: [
      { item: "Bell peppers", qty: "4", note: "tops cut, seeded" },
      { item: "Ground turkey", qty: "400g" },
      { item: "Cooked rice", qty: "1 cup" },
      { item: "Onion", qty: "1/2", note: "diced" },
      { item: "Marinara sauce", qty: "1 cup" },
      { item: "Shredded cheese", qty: "1/2 cup" },
      { item: "Olive oil", qty: "1 tbsp" },
      { item: "Salt + pepper", qty: "to taste" },
    ],
    steps: [
      { title: "Preheat", body: "Preheat the oven to two hundred degrees Celsius, four hundred Fahrenheit." },
      {
        title: "Brown the filling",
        body: "Heat the olive oil in a pan, cook the onion until soft, then add the turkey and cook until no pink remains, about six minutes.",
        timer: { seconds: 360, label: "Turkey brown" },
      },
      { title: "Mix the filling", body: "Stir the rice and half the marinara into the turkey and season with salt and pepper." },
      { title: "Stuff the peppers", body: "Stand the peppers in a baking dish, spoon the filling into each, then top with the remaining marinara and the cheese." },
      {
        title: "Bake",
        body: "Bake until the peppers are tender and the cheese is melted, about twenty-five minutes.",
        timer: { seconds: 1500, label: "Peppers bake" },
      },
    ],
  },
  {
    slug: "teriyaki-tofu-bowl",
    name: "Teriyaki tofu rice bowl",
    category: "Dinner",
    angle: "Veggie & high-protein",
    calories: [500, 700],
    protein: [25, 40],
    minutes: 18,
    tags: ["Vegetarian"],
    ingredients: [
      { item: "Firm tofu", qty: "250g", note: "pressed and cubed" },
      { item: "Cooked rice", qty: "1 cup" },
      { item: "Teriyaki sauce", qty: "3 tbsp" },
      { item: "Broccoli", qty: "1.5 cups", note: "florets" },
      { item: "Cornstarch", qty: "1 tbsp" },
      { item: "Olive oil", qty: "1 tbsp" },
      { item: "Sesame seeds", qty: "1 tsp" },
    ],
    steps: [
      { title: "Coat the tofu", body: "Press the tofu, cut it into cubes, and toss with the cornstarch until lightly coated — this is what makes it crisp." },
      {
        title: "Crisp the tofu",
        body: "Heat the olive oil in a pan over medium-high and cook the tofu, turning, until golden on all sides, about eight minutes.",
        timer: { seconds: 480, label: "Tofu crisp" },
      },
      {
        title: "Steam the broccoli",
        body: "Add the broccoli with a splash of water, cover, and steam until bright green, about three minutes.",
        timer: { seconds: 180, label: "Broccoli steam" },
      },
      { title: "Glaze", body: "Pour the teriyaki sauce over the tofu and broccoli and toss until everything is sticky and coated." },
      { title: "Serve", body: "Spoon it over the rice and scatter sesame seeds across." },
    ],
  },

  // Snacks
  {
    slug: "protein-hot-chocolate",
    name: "Protein hot chocolate",
    category: "Snacks",
    angle: "Sweet, warm, protein-y",
    calories: [150, 300],
    protein: [20, 35],
    minutes: 4,
    tags: ["Drink"],
    ingredients: [
      { item: "Milk", qty: "1 cup" },
      { item: "Chocolate protein powder", qty: "1 scoop" },
      { item: "Cocoa powder", qty: "1 tsp" },
      { item: "Honey", qty: "1 tsp" },
      { item: "Salt", qty: "1 pinch" },
    ],
    steps: [
      {
        title: "Warm the milk",
        body: "Heat the milk in a small pot over medium heat until steaming but not boiling, about three minutes.",
        timer: { seconds: 180, label: "Milk warm" },
      },
      { title: "Bloom the cocoa", body: "Whisk in the cocoa powder and honey until fully dissolved." },
      { title: "Cool slightly", body: "Take the pot off the heat and let it sit for one minute so the protein powder won't clump." },
      { title: "Add the protein", body: "Whisk in the protein powder and a pinch of salt until smooth and frothy, then pour into a mug." },
    ],
  },
  {
    slug: "cottage-dessert-bowl",
    name: "Cottage cheese dessert bowl",
    category: "Snacks",
    angle: "Sweet snack, no cook",
    calories: [250, 400],
    protein: [25, 35],
    minutes: 2,
    tags: ["No cook"],
    ingredients: [
      { item: "Cottage cheese", qty: "1 cup" },
      { item: "Honey", qty: "1 tbsp" },
      { item: "Berries", qty: "1/2 cup" },
      { item: "Dark chocolate", qty: "1 tbsp", note: "chopped" },
      { item: "Cinnamon", qty: "1 pinch" },
    ],
    steps: [
      { title: "Spoon the base", body: "Spoon the cottage cheese into a bowl and smooth the top." },
      { title: "Sweeten", body: "Drizzle the honey over and dust with a pinch of cinnamon." },
      { title: "Top it", body: "Scatter the berries and chopped dark chocolate across, then eat right away." },
    ],
  },
  {
    slug: "yogurt-cookie-dough",
    name: "Greek yogurt cookie dough bowl",
    category: "Snacks",
    angle: "Dessert-feel, real macros",
    calories: [250, 450],
    protein: [25, 40],
    minutes: 5,
    tags: ["Sweet"],
    ingredients: [
      { item: "Greek yogurt", qty: "1 cup" },
      { item: "Almond flour", qty: "2 tbsp" },
      { item: "Vanilla protein powder", qty: "1/2 scoop" },
      { item: "Maple syrup", qty: "1 tsp" },
      { item: "Chocolate chips", qty: "1 tbsp" },
      { item: "Vanilla extract", qty: "1/4 tsp" },
    ],
    steps: [
      { title: "Toast the flour", body: "Briefly toast the almond flour in a dry pan over low heat until just fragrant, about one minute, then let it cool — this removes the raw taste." },
      { title: "Mix the base", body: "Stir the Greek yogurt with the protein powder, maple syrup, and vanilla until smooth." },
      { title: "Add the texture", body: "Fold in the cooled almond flour until the mixture thickens like cookie dough." },
      { title: "Finish", body: "Stir in most of the chocolate chips, spoon into a bowl, and scatter the rest on top." },
    ],
  },
  {
    slug: "apple-yogurt-plate",
    name: "Apple cinnamon yogurt plate",
    category: "Snacks",
    angle: "Filling & sweet",
    calories: [250, 400],
    protein: [20, 35],
    minutes: 3,
    tags: ["No cook"],
    ingredients: [
      { item: "Apple", qty: "1", note: "sliced" },
      { item: "Greek yogurt", qty: "3/4 cup" },
      { item: "Peanut butter", qty: "1 tbsp" },
      { item: "Cinnamon", qty: "1/4 tsp" },
      { item: "Honey", qty: "1 tsp" },
      { item: "Granola", qty: "1 tbsp" },
    ],
    steps: [
      { title: "Spoon the yogurt", body: "Spoon the Greek yogurt into the center of a plate or shallow bowl." },
      { title: "Slice the apple", body: "Slice the apple thin and fan the pieces around the yogurt." },
      { title: "Top it", body: "Drizzle the peanut butter and honey over, then dust everything with cinnamon." },
      { title: "Finish", body: "Scatter the granola over the yogurt for crunch." },
    ],
  },
  {
    slug: "banana-bites",
    name: "Air fryer protein banana bites",
    category: "Snacks",
    angle: "Sweet, better macros",
    calories: [250, 450],
    protein: [15, 30],
    minutes: 12,
    tags: ["Air fryer"],
    ingredients: [
      { item: "Banana", qty: "2", note: "sliced thick" },
      { item: "Vanilla protein powder", qty: "2 tbsp" },
      { item: "Cinnamon", qty: "1/2 tsp" },
      { item: "Olive oil spray", qty: "as needed" },
      { item: "Honey", qty: "1 tsp" },
    ],
    steps: [
      { title: "Preheat", body: "Preheat the air fryer to one hundred eighty degrees Celsius, three hundred fifty Fahrenheit." },
      { title: "Coat the banana", body: "Slice the bananas thick, then toss the rounds with the protein powder and cinnamon until lightly dusted." },
      { title: "Arrange", body: "Mist the air fryer basket and lay the banana rounds in one layer so they don't touch." },
      {
        title: "Air fry",
        body: "Cook for eight minutes until soft and caramelized at the edges.",
        timer: { seconds: 480, label: "Air fry banana" },
      },
      { title: "Finish", body: "Drizzle the honey over the bites while they're still warm." },
    ],
  },
  {
    slug: "protein-pudding",
    name: "High-protein chocolate pudding",
    category: "Snacks",
    angle: "Dessert, no stove",
    calories: [200, 350],
    protein: [25, 40],
    minutes: 3,
    tags: ["No cook"],
    ingredients: [
      { item: "Greek yogurt", qty: "1 cup" },
      { item: "Chocolate protein powder", qty: "1 scoop" },
      { item: "Cocoa powder", qty: "1 tsp" },
      { item: "Milk", qty: "2 tbsp" },
      { item: "Maple syrup", qty: "1 tsp" },
    ],
    steps: [
      { title: "Combine", body: "Add the Greek yogurt, protein powder, cocoa powder, and maple syrup to a bowl." },
      { title: "Whisk smooth", body: "Whisk hard, adding the milk a splash at a time, until the pudding is thick and silky with no lumps." },
      { title: "Chill or serve", body: "Eat it right away, or let it sit in the fridge for a few minutes to firm up." },
    ],
  },
  {
    slug: "turkey-rollups",
    name: "Turkey cucumber roll-ups",
    category: "Snacks",
    angle: "Protein in a minute",
    calories: [150, 300],
    protein: [20, 35],
    minutes: 2,
    tags: ["No cook"],
    ingredients: [
      { item: "Sliced turkey breast", qty: "6 slices" },
      { item: "Cream cheese", qty: "2 tbsp" },
      { item: "Cucumber", qty: "1", note: "cut into spears" },
      { item: "Everything bagel seasoning", qty: "1 tsp" },
    ],
    steps: [
      { title: "Spread the base", body: "Lay the turkey slices flat and spread a thin layer of cream cheese over each." },
      { title: "Add the cucumber", body: "Place a cucumber spear at the edge of each slice." },
      { title: "Roll", body: "Roll each turkey slice tightly around the cucumber." },
      { title: "Finish", body: "Sprinkle the everything bagel seasoning over the roll-ups." },
    ],
  },
  {
    slug: "protein-coffee",
    name: "Protein coffee",
    category: "Snacks",
    angle: "Caffeine + 25g protein",
    calories: [120, 250],
    protein: [20, 35],
    minutes: 4,
    tags: ["Drink"],
    ingredients: [
      { item: "Brewed coffee", qty: "1 cup", note: "cooled slightly" },
      { item: "Vanilla protein powder", qty: "1 scoop" },
      { item: "Milk", qty: "1/4 cup" },
      { item: "Ice", qty: "1 cup" },
      { item: "Cinnamon", qty: "1 pinch" },
    ],
    steps: [
      { title: "Cool the coffee", body: "Brew the coffee and let it cool for a couple of minutes — hot coffee makes protein powder clump." },
      { title: "Blend", body: "Add the coffee, protein powder, milk, and ice to a blender and blend until smooth and frothy." },
      { title: "Serve", body: "Pour over fresh ice and dust with a pinch of cinnamon." },
    ],
  },
  {
    slug: "rice-cake-snack",
    name: "Rice cake protein snack",
    category: "Snacks",
    angle: "Pre-workout & sweet",
    calories: [200, 400],
    protein: [15, 30],
    minutes: 2,
    tags: ["Pre-workout"],
    ingredients: [
      { item: "Rice cakes", qty: "2" },
      { item: "Peanut butter", qty: "2 tbsp" },
      { item: "Banana", qty: "1", note: "sliced" },
      { item: "Honey", qty: "1 tsp" },
      { item: "Chia seeds", qty: "1 tsp" },
    ],
    steps: [
      { title: "Spread the base", body: "Spread a tablespoon of peanut butter over each rice cake." },
      { title: "Add the banana", body: "Lay the banana slices across the peanut butter." },
      { title: "Finish", body: "Drizzle the honey over and sprinkle with chia seeds." },
    ],
  },
  {
    slug: "frozen-yogurt-bark",
    name: "Frozen yogurt bark",
    category: "Snacks",
    angle: "Meal-prep dessert",
    calories: [150, 250],
    protein: [10, 20],
    minutes: 10,
    tags: ["Meal prep"],
    ingredients: [
      { item: "Greek yogurt", qty: "2 cups" },
      { item: "Honey", qty: "2 tbsp" },
      { item: "Berries", qty: "1/2 cup" },
      { item: "Dark chocolate", qty: "2 tbsp", note: "chopped" },
      { item: "Granola", qty: "2 tbsp" },
    ],
    steps: [
      { title: "Mix the base", body: "Stir the Greek yogurt with the honey until smooth and even." },
      { title: "Spread it", body: "Line a tray with parchment and spread the yogurt into an even layer about a centimeter thick." },
      { title: "Add toppings", body: "Scatter the berries, chopped chocolate, and granola across the surface, pressing them in lightly." },
      {
        title: "Freeze",
        body: "Slide the tray into the freezer and freeze until completely solid, about four hours.",
        timer: { seconds: 14400, label: "Freeze bark" },
      },
      { title: "Break and serve", body: "Once solid, lift the bark off the parchment and break it into shards. Keep extras in the freezer." },
    ],
  },
];

export const CATEGORIES: RecipeCategory[] = ["Breakfast", "Lunch", "Dinner", "Snacks"];

export function getRecipeBySlug(slug: string | null | undefined): Recipe | null {
  if (!slug) return null;
  return RECIPES.find((r) => r.slug === slug) ?? null;
}
