export type StepCommand = 'next' | 'begin' | 'back';

// Messages generated by screen taps (as opposed to spoken input) carry this
// prefix. detectStepCommand ignores them, so a tap can never advance the
// step twice — once locally and once via its own transcript.
export const SCREEN_ACTION_PREFIX = 'Screen update:';

export function screenStepMessage(index: number): string {
  return `${SCREEN_ACTION_PREFIX} I moved to step ${index} on the screen. Walk me through it.`;
}

export function screenCompletedMessage(): string {
  return `${SCREEN_ACTION_PREFIX} the dish is plated and the screen shows the recipe as complete.`;
}

// Classifies a short utterance. 'next' means the user finished the step they
// are looking at ("done"); 'begin' is a soft go-ahead ("ready") that starts
// step 1 when nothing is highlighted yet and behaves like 'next' afterwards.
// Long utterances are ignored — they are conversation, not commands.
export function detectStepCommand(message: string): StepCommand | null {
  if (message.startsWith(SCREEN_ACTION_PREFIX)) return null;
  const norm = message
    .toLowerCase()
    .replace(/[^a-z\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  const wordCount = norm ? norm.split(' ').length : 0;
  if (wordCount === 0 || wordCount > 7) return null;
  if (/\b(repeat|again)\b/.test(norm)) return null;
  if (/\b(back|previous|go back)\b/.test(norm)) return 'back';
  if (/\b(done|finished|next|next step|move on)\b/.test(norm)) return 'next';
  if (
    /\b(ready|continue|proceed|go on|keep going|got it|all set|start|begin)\b/.test(
      norm,
    )
  ) {
    return 'begin';
  }
  return null;
}

export type StepPosition = { index: number; total: number };

export type StepMove =
  | { kind: 'go'; index: number; total: number }
  | { kind: 'complete' }
  | { kind: 'stay' };

// current === null means no step is highlighted yet. The screen displays
// step 1 in that state, so a completion word moves past it (to step 2) while
// a kickoff word lands on it.
export function resolveStepMove(
  cmd: StepCommand,
  current: StepPosition | null,
  recipeStepCount: number,
): StepMove {
  const total = current?.total ?? recipeStepCount;
  if (cmd === 'back') {
    if (!current || current.index <= 1) return { kind: 'stay' };
    return {
      kind: 'go',
      index: current.index - 1,
      total: total > 0 ? total : current.index,
    };
  }
  const target =
    cmd === 'begin' && !current ? 1 : Math.max(current?.index ?? 1, 1) + 1;
  if (total > 0 && target > total) return { kind: 'complete' };
  return { kind: 'go', index: target, total: total > 0 ? total : target };
}
